# Generated by Django 5.1.15 on 2026-06-11 06:55

from django.db import migrations, models
from django.db.models import Avg


def populate_ratings(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    ProductReview = apps.get_model('shop', 'ProductReview')
    for product in Product.objects.all():
        reviews = ProductReview.objects.filter(product=product)
        count = reviews.count()
        if count > 0:
            avg_rating = reviews.aggregate(avg=Avg('rating'))['avg'] or 0.0
        else:
            avg_rating = 0.0
        product.average_rating = avg_rating
        product.review_count = count
        product.save(update_fields=['average_rating', 'review_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_is_active_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(populate_ratings, reverse_code=migrations.RunPython.noop),
    ]
